"""Benchmark a low-resolution Stage-1 preview generated by the full LTX-2.3 22B model.

This standalone root-level demo deliberately does not change any package source.  It
implements only Stage 1 of ``TI2VidTwoStagesPipeline``: there is no latent
upsampling and no Stage 2 refinement.  The resulting MP4 is a performance preview,
not a final production render.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import torch

from ltx_core.components.guiders import MultiModalGuiderParams, create_multimodal_guider_factory
from ltx_core.components.noisers import GaussianNoiser
from ltx_core.components.schedulers import LTX2Scheduler
from ltx_core.model.video_vae import TilingConfig, get_video_chunks_number
from ltx_core.types import Audio, SpatioTemporalScaleFactors, VideoPixelShape
from ltx_pipelines.utils.blocks import AudioDecoder, DiffusionStage, ImageConditioner, PromptEncoder, VideoDecoder
from ltx_pipelines.utils.denoisers import FactoryGuidedDenoiser
from ltx_pipelines.utils.helpers import assert_resolution, combined_image_conditionings, get_device
from ltx_pipelines.utils.media_io import encode_video
from ltx_pipelines.utils.types import ModalitySpec, OffloadMode

MODEL_ROOT = Path("./models")
CHECKPOINT_RELATIVE_PATH = Path("LTX-2.3/ltx-2.3-22b-dev.safetensors")
GEMMA_RELATIVE_PATH = Path("gemma-3-12b-it-qat-q4_0-unquantized")
PREVIEW_HEIGHT = 384
PREVIEW_WIDTH = 640
FRAME_RATE = 24.0
DEFAULT_STEPS = 8
DEFAULT_OFFLOAD = OffloadMode.DISK


def duration_to_num_frames(duration_seconds: float) -> int:
    """Return the largest LTX-compatible frame count within the requested duration."""
    if not torch.isfinite(torch.tensor(duration_seconds)) or duration_seconds <= 0:
        raise ValueError("duration-seconds must be a finite positive number")
    requested_frames = max(1, round(duration_seconds * FRAME_RATE))
    time_scale = SpatioTemporalScaleFactors.default().time
    frames = ((requested_frames - 1) // time_scale) * time_scale + 1
    if frames < time_scale + 1:
        raise ValueError(f"duration-seconds must produce at least {time_scale + 1} frames")
    return frames


@dataclass(frozen=True)
class BenchmarkResult:
    video: Iterator[torch.Tensor]
    audio: Audio
    sample_seconds: float
    prompt_seconds: float
    decode_seconds: float


class FullModelFastPreview:
    """Full-model Stage-1-only adapter matching TI2VidTwoStagesPipeline semantics."""

    def __init__(self, checkpoint_path: Path, gemma_root: Path, offload_mode: OffloadMode) -> None:
        self.device = get_device()
        self.dtype = torch.bfloat16
        self.scheduler = LTX2Scheduler()
        self.prompt_encoder = PromptEncoder(
            str(checkpoint_path), str(gemma_root), self.dtype, self.device, offload_mode=offload_mode
        )
        self.image_conditioner = ImageConditioner(str(checkpoint_path), self.dtype, self.device)
        self.stage_1 = DiffusionStage(
            str(checkpoint_path), self.dtype, self.device, loras=(), offload_mode=offload_mode
        )
        self.video_decoder = VideoDecoder(str(checkpoint_path), self.dtype, self.device)
        self.audio_decoder = AudioDecoder(str(checkpoint_path), self.dtype, self.device)

    @torch.inference_mode()
    def generate(
        self,
        *,
        prompt: str,
        negative_prompt: str,
        seed: int,
        height: int,
        width: int,
        num_frames: int,
        steps: int,
    ) -> BenchmarkResult:
        assert_resolution(height=height, width=width, is_two_stage=True)
        generator = torch.Generator(device=self.device).manual_seed(seed)
        noiser = GaussianNoiser(generator=generator)

        prompt_started = time.perf_counter()
        positive_context, negative_context = self.prompt_encoder(
            [prompt, negative_prompt], enhance_first_prompt=False, enhance_prompt_image=None, enhance_prompt_seed=seed
        )
        _synchronize(self.device)
        prompt_seconds = time.perf_counter() - prompt_started

        stage_shape = VideoPixelShape(
            batch=1, frames=num_frames, width=width // 2, height=height // 2, fps=FRAME_RATE
        )
        conditionings = self.image_conditioner(
            lambda encoder: combined_image_conditionings(
                images=[],
                height=stage_shape.height,
                width=stage_shape.width,
                video_encoder=encoder,
                dtype=self.dtype,
                device=self.device,
            )
        )
        sigmas = self.scheduler.execute(steps=steps).to(dtype=torch.float32, device=self.device)
        denoiser = FactoryGuidedDenoiser(
            v_context=positive_context.video_encoding,
            a_context=positive_context.audio_encoding,
            video_guider_factory=create_multimodal_guider_factory(
                params=MultiModalGuiderParams(), negative_context=negative_context.video_encoding
            ),
            audio_guider_factory=create_multimodal_guider_factory(
                params=MultiModalGuiderParams(), negative_context=negative_context.audio_encoding
            ),
        )

        sample_started = time.perf_counter()
        video_state, audio_state = self.stage_1(
            denoiser=denoiser,
            sigmas=sigmas,
            noiser=noiser,
            width=stage_shape.width,
            height=stage_shape.height,
            frames=num_frames,
            fps=FRAME_RATE,
            video=ModalitySpec(context=positive_context.video_encoding, conditionings=conditionings),
            audio=ModalitySpec(context=positive_context.audio_encoding),
        )
        _synchronize(self.device)
        sample_seconds = time.perf_counter() - sample_started

        decode_started = time.perf_counter()
        video = self.video_decoder(video_state.latent, TilingConfig.default(), generator)
        audio = self.audio_decoder(audio_state.latent)
        _synchronize(self.device)
        return BenchmarkResult(
            video=_wrap_inference_iterator(video),
            audio=audio,
            sample_seconds=sample_seconds,
            prompt_seconds=prompt_seconds,
            decode_seconds=time.perf_counter() - decode_started,
        )


def _wrap_inference_iterator(video: Iterator[torch.Tensor]) -> Iterator[torch.Tensor]:
    """Expose a lazy video iterator without dropping inference mode."""
    with torch.inference_mode():
        yield from video


def _synchronize(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.synchronize(device)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--negative-prompt", default="")
    parser.add_argument("--model-root", type=Path, default=MODEL_ROOT)
    parser.add_argument("--checkpoint", type=Path, default=CHECKPOINT_RELATIVE_PATH)
    parser.add_argument("--duration-seconds", type=float, default=5.0)
    parser.add_argument("--steps", type=int, default=DEFAULT_STEPS)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--offload", choices=[mode.value for mode in OffloadMode], default=DEFAULT_OFFLOAD.value)
    parser.add_argument("--output-path", type=Path, default=Path("outputs/full-model-fast.mp4"))
    parser.add_argument("--metrics-path", type=Path, default=Path("outputs/full-model-fast.metrics.json"))
    args = parser.parse_args()
    if args.steps <= 0:
        raise ValueError("steps must be positive")

    checkpoint_path = args.model_root / args.checkpoint
    gemma_root = args.model_root / GEMMA_RELATIVE_PATH
    if not checkpoint_path.is_file():
        raise FileNotFoundError(f"full-model checkpoint not found: {checkpoint_path}")
    if not gemma_root.is_dir():
        raise FileNotFoundError(f"Gemma directory not found: {gemma_root}")

    num_frames = duration_to_num_frames(args.duration_seconds)
    started = time.perf_counter()
    preview = FullModelFastPreview(checkpoint_path, gemma_root, OffloadMode(args.offload))
    result = preview.generate(
        prompt=args.prompt,
        negative_prompt=args.negative_prompt,
        seed=args.seed,
        height=PREVIEW_HEIGHT * 2,
        width=PREVIEW_WIDTH * 2,
        num_frames=num_frames,
        steps=args.steps,
    )
    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    encode_started = time.perf_counter()
    encode_video(
        video=result.video,
        fps=FRAME_RATE,
        audio=result.audio,
        output_path=args.output_path,
        video_chunks_number=get_video_chunks_number(num_frames, TilingConfig.default()),
    )
    _synchronize(preview.device)
    encode_seconds = time.perf_counter() - encode_started
    total_seconds = time.perf_counter() - started
    metrics = {
        "checkpoint": str(checkpoint_path),
        "offload": args.offload,
        "steps": args.steps,
        "seed": args.seed,
        "frames": num_frames,
        "fps": FRAME_RATE,
        "preview_resolution": [PREVIEW_WIDTH, PREVIEW_HEIGHT],
        "prompt_seconds": round(result.prompt_seconds, 3),
        "stage_1_sample_seconds": round(result.sample_seconds, 3),
        "decode_setup_seconds": round(result.decode_seconds, 3),
        "encode_seconds": round(encode_seconds, 3),
        "total_seconds": round(total_seconds, 3),
    }
    args.metrics_path.parent.mkdir(parents=True, exist_ok=True)
    args.metrics_path.write_text(json.dumps(metrics, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    sys.stdout.write(json.dumps(metrics, ensure_ascii=False, indent=2) + "\n")


if __name__ == "__main__":
    main()
